version: '3.4'

services:
  challengeml:
    image: challengeml
    #restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: clientes
      DB_USER: diegomb
      DB_PASSWORD: DDD111+
    volumes:
      - .:/app
    ports:
      - 8000:80
    #command: ["tail", "-f", "/dev/null"]
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: bdclientes
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: diegomb
      POSTGRES_PASSWORD: DDD111+
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 5432:5432

